[Unit]
# Type=dbus holds the initial start job until the actual daemon owns its name.
Before=lightdm.service

[Service]
ExecStart=
ExecStart=/usr/local/sbin/utxperia-biometryd
RestartPreventExitStatus=
SuccessExitStatus=
Restart=on-failure
RestartSec=5
TimeoutStartSec=45
KillMode=control-group
